### ISSUE TITLE
Refreshenv has a dependency on chocolatey

### ISSUE THREAD

**Issue by Rick-van-Dam** [avivasolutionsnl/mercury-demo#1]
Find a way to get the same functionality as `refreshenv` without depending on chocolatey. It should refresh the PATH variables so that you can use the installed applications right away without restarting.

We current use it [here](https://github.com/avivasolutionsnl/mercury-demo/blob/master/setup.ps1#L67)

The script in this link might be of use (what chocolatey uses internally?)
https://www.reddit.com/r/PowerShell/comments/9gnwat/cmdlet_not_recognized_unless_i_start_a_new/

**Comment by joostmeijles** [comment]
Or simply remove the `refreshenv` step and add a close/open instruction to the README.

**Comment by Rick-van-Dam** [comment]
Testing concluded that that is not enough unfortunately. What does work is restarting the OS which is a option (reproduced on multiple machines and multiple persons by now).
